config/routes.rb
Thoughtsy::Application.routes.draw do
  get "password_resets/new"
  resources :users do
    resources :messages,  only: [:show, :index, :new]
  end
  resources :sessions,  only: [:new, :create, :destroy]
  resources :posts,     except: [:update, :edit] do
    resources :responses, only: [:new, :create]
    member do
      get 'flag'
      get 'language'
    end
    get 'queue', on: :collection
  end
  resources :ratings,   only: :create
  resources :responses, only: [:show, :destroy, :index]
  resources :password_resets, except: [:show, :index]
  resources :messages,  only: [:create, :destroy] do
    put 'view', on: :member
  end

  resources :images, only: [:new] do
    get 'remove', on: :collection
  end

  root 'static_pages#home'
  
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/team',    to: 'static_pages#team',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/queue',   to: 'posts#queue',          via: 'get'

  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <% if object.instance_of?(User) %>
      <p class="center">
        The form contains <%= pluralize(object.errors.count, "error") %>
      </p>
    <% end %>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: "alert alert-#{key}", :"data-dismiss" => "alert") %>
<% end %>

app/views/shared/_form.html.erb
<div id="thought_form">
  <div class="panel-focus">
    <div class="panel-focus panel-post">
      <% if form.instance_of?(Post) %>
        <%= form_for(@post) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.text_area :content, class: "form-control", rows: "5", placeholder: "your thought..." %>
          <%= f.hidden_field :key %>
          <%= button_tag "Post", class: "btn btn-primary", id: "post_button", data: { 'loading-text' => "Posting..." } %>
          <span class="pull-right">
            <% unless @post.has_image_upload? %>
              <%= link_to("Upload an image", new_image_path, :remote => true) %>
            <% else %>
              <strong>Image: </strong><%= form.image_name %>
              | <%= link_to("remove", remove_images_path(key: params[:key])) %>
            <% end %>
          </span>
        <% end %>
      <% else %>
        <%= form_for([@post, @response]) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <%= f.text_area :content, class: "form-control", rows: "5", placeholder: "your thought..." %>
          <%= f.hidden_field :key %>
          <%= button_tag "Respond", class: "btn btn-primary", id: "post_button", data: { 'loading-text' => "Responding..." } %>
          <%= f.hidden_field :post_id, value: @post.id %>
          <span class="pull-right">
            <% unless @response.has_image_upload? %>
              <%= link_to("Upload an image", new_image_path(post_id: @post.id), :remote => true) %>
            <% else %>
              <strong>Image: </strong><%= @response.image_name %>
              | <%= link_to("remove", remove_images_path(key: params[:key], post_id: @post.id)) %>
            <% end %>
          </span>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<div class="modal" id="imageModal" style="display:none;">
</div>

<script>
  $('#post_button').click(function(){
    $(this).button('loading');
  });
</script>

app/views/shared/_image_fields.html.erb
<!-- Reply Modal -->
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h3 class="modal-title center" id="uploadImage">Image Upload</h3>
    </div>
    <div class="modal-body">
      <%= direct_upload_form_for @uploader do |f| %>
        <span id="input_button">
          <button class="btn btn-primary" id="image_button">Choose an image</button>
          <%= f.file_field :image, id: "picture" %>
        </span>
        <%= button_tag "Upload", class: "btn btn-primary", id: "upload_button", data: { 'loading-text' => "Uploading..." } %>
        <div id="image_filename"><p>*.jpg, *.png, *.jpeg, or *.gif</p></div>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <p class="center">* Uploading an image will refresh the form.  All unsaved data will be lost. *</p>
      <% end %>
    </div>
  </div>
</div>

<!-- Displays chosen file name in custom styled button -->
<script>
  $('#upload_button').hide();
  $('#picture').change(function(e) {
    var filepath = this.value;
    var m = filepath.match(/([^\/\\]+)$/);
    var filename = m[1];
    $('#image_filename').html("<p><strong>Image: </strong>" + filename + "</p>");
    $('#upload_button').show();
  });
  $('#upload_button').click(function(){
    $(this).button('loading');
  });
</script>

app/views/shared/_social_links.html.erb
<div id="social_links">
  <% if @rateable.class.name == 'Response' %>
    <a href="https://twitter.com/intent/tweet?url=<%= post_url(@rateable.post) %>&text=<%= wrapped(@rateable.content, 65) unless @rateable.content.nil? %>&via=Thoughtsy" target="_blank">
      <i class="fa fa-twitter"></i>
    </a>

    <a href="https://facebook.com/sharer.php?u=<%= post_url(@rateable.post) %>" target="_blank">
      <i class="fa fa-facebook"></i>
    </a>

    <a href="https://plus.google.com/share?url=<%= post_url(@rateable.post) %>" target="_blank">
      <i class="fa fa-google-plus"></i>
    </a>

    <% if @rateable.image? %>
      <a href="http://pinterest.com/pin/create/button/?url=<%= post_url(@rateable.post) %>&description=A+great+post+from+Thoughtsy.com&media=<%= image_url(@rateable) %>" target="_blank">
        <i class="fa fa-pinterest"></i>
      </a>
      <!-- everything after second url is optional for adding description or photo
           Haven't tested in browser because I don't have an account
       -->
    <% end %>

    <a href="mailto:?subject=A great response on Thoughtsy.com&body=I thought you might find this interesting%0d%0a%0d%0a<%= post_url(@rateable.post) %>" target="_blank">
      <i class="fa fa-envelope"></i>
    </a>
  <% else %>
    <a href="https://twitter.com/intent/tweet?url=<%= post_url(@rateable) %>&text=<%= wrapped(@rateable.content, 100) unless @rateable.content.nil? %>&via=Thoughtsy" target="_blank">
      <i class="fa fa-twitter"></i>
    </a>

    <a href="https://facebook.com/sharer.php?u=<%= post_url(@rateable) %>" target="_blank">
      <i class="fa fa-facebook"></i>
    </a>

    <a href="https://plus.google.com/share?url=<%= post_url(@rateable) %>" target="_blank">
      <i class="fa fa-google-plus"></i>
    </a>

    <% if @rateable.image? %>
      <a href="http://pinterest.com/pin/create/button/?url=<%= post_url(@rateable) %>&description=A+great+post+from+Thoughtsy.com&media=<%= image_url(@rateable) %>" target="_blank">
        <i class="fa fa-pinterest"></i>
      </a>
      <!-- everything after second url is optional for adding description or photo
           Haven't tested in browser because I don't have an account
       -->
    <% end %>

    <a href="mailto:?subject=A great response on Thoughtsy.com&body=I thought you might find this interesting%0d%0a%0d%0a<%= post_url(@rateable) %>" target="_blank">
      <i class="fa fa-envelope"></i>
    </a>
  <% end %>
</div>



<!-- 
<a href="http://www.linkedin.com/shareArticle?mini=true&
  url=YOURURLHERE" target="_blank">LinkedIn</a>

<a href="http://digg.com/submit?
  url=YOURURLHERE" target="_blank">Digg</a>

<a href="http://reddit.com/submit?url=YOURURLHERE&title=A great response on Thoughtsy.com" target="_blank">
</a>
 -->

app/views/shared/_thought.html.erb
<div class="thought" id="<%= thought.id %>">
  <% profile = false unless local_assigns.has_key? :profile %>

  <div class="thought_content">
    <% if profile %>
      <% if thought.instance_of?(Response) %>
        <%= render partial: 'shared/thumb', object: thought %>
        <%= link_to wrapped(thought.content, 200), post_path(thought.post) unless thought.content.nil? %>
      <% else %>
        <%= render partial: 'shared/thumb', object: thought %>
        <%= link_to wrapped(thought.content, 200), post_path(thought) unless thought.content.nil? %>
      <% end %>
    <% else %>
      <% if thought.image.present? %>
        <% if thought.image_processed? %>
          <%= image_tag thought.image_url, class: "img-responsive" %>
        <% else %>
          <em>Processing...</em>
        <% end %>
      <% end %>
      <%= custom_format(thought.content) unless thought.content.nil? %>
    <% end %>
  </div>

  <div class="thought_author">
    <% unless profile %>
      <%= link_to "#{thought.user.username}", user_path(thought.user) %>
      <span class="user_score"> | <%= thought.user.score %></span>
    <% end %>
    <span class="timestamp pull-right"><%= created_time(thought) %></span>
  </div>
</div>

app/views/shared/_thumb.html.erb
<% if thumb.image.present? %>
  <% if thumb.image_processed? %>
    <%= link_to image_tag(thumb.image_url(:thumb)), post_path(thumb.post) if thumb.instance_of?(Response) %>
    <%= link_to image_tag(thumb.image_url(:thumb)), post_path(thumb) if thumb.instance_of?(Post) %>
  <% else %>
    <em>Processing...</em>
  <% end %>
<% end %>