config/routes.rb
Thoughtsy::Application.routes.draw do
  get "password_resets/new"
  resources :users do
    resources :messages,  only: [:show, :index, :new]
  end
  resources :sessions,  only: [:new, :create, :destroy]
  resources :posts,     except: [:update, :edit] do
    resources :responses, only: [:new, :create]
    member do
      get 'flag'
      get 'language'
    end
    get 'queue', on: :collection
  end
  resources :ratings,   only: :create
  resources :responses, only: [:show, :destroy, :index]
  resources :password_resets, except: [:show, :index]
  resources :messages,  only: [:create, :destroy] do
    put 'view', on: :member
  end

  resources :images, only: [:new] do
    get 'remove', on: :collection
  end

  root 'static_pages#home'
  
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/team',    to: 'static_pages#team',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/queue',   to: 'posts#queue',          via: 'get'

  

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_action :signed_in_user
  before_action :tokened_responder, only: :create

  after_action  :accept_and_set_tokens, only: :new

  def new 
    @post = Post.find(params[:post_id])
    @response = @post.responses.new(key: params[:key])
    @rating = Rating.new
  end

  def show  # Ratings Page #
    @response = Response.find(params[:id])
    @post = @response.post
    @rating = Rating.new
  end

  def create
    @response = current_user.responses.build(response_params)
    @post = Post.find(params[:post_id])
    if @response.save
      @response.enqueue_image
      @response.update_all
      flash[:success] = "Response sent!"
      redirect_to posts_path
    else
      @post
      @rating = Rating.new
      render 'new'
    end
  end

private

  def response_params
    params.require(:response).permit(:content, :post_id, :image, :key)
  end

  def accept_and_set_tokens
    post = Post.find(params[:post_id])
    current_user.set_tokens(post.id)
    post.accept!
    post.add_unavailable_users(current_user)
  end
end


# before_action :admin_user, only: :destroy

# def destroy
#   @response = Response.find(params[:id])
#   @post = @response.post
#   # @post.unanswer!
#   @response.destroy
#   flash[:success] = "Response destroyed!"
#   redirect_to post_path(@post)
# end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<div id="response_form">
  <div class="panel-focus">
    <div class="panel-focus panel-response">
      <%= form_for([@post, @response]) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.text_area :content, class: "form-control", rows: "5", placeholder: "your response..." %>
        <%= f.submit "Respond", class: "btn btn-primary" %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <%= f.hidden_field :key %>
        <span class="pull-right">
          <% unless @response.has_image_upload? %>
            <%= link_to("Upload an image", new_image_path(post_id: @post.id), :remote => true) %>
          <% else %>
            <strong>Image: </strong><%= @response.image_name %>
            | <%= link_to("remove", remove_images_path(key: params[:key], post_id: @post.id)) %>
          <% end %>
        </span>
      <% end %>
    </div>
  </div>
</div>

<div class="modal" id="imageModal" style="display:none;">
</div>

app/views/responses/_responder_links.html.erb
<div id="responder_links">
  <span class="pull-left">
    <small><%= link_to "inappropriate post?", flag_post_path(@post.id) %></small>
  </span>
  <span class="pull-right">
    <small><%= link_to "not your language?", language_post_path(@post.id) %></small>
  </span>
  <%= render partial: 'ratings/form', locals: { rateable: @post } %>
</div>

app/views/responses/index.html.erb
<% provide(:page_title, "Responses") %>

<div class="row-fluid">
  <div class="span8 offset2">
    <div class="well darker" id="thought">
      <%= render partial: "shared/thought", object: @post %>
    </div>
  </div>
</div>

<div class="row-fluid">  
  <div class="span6 offset3">
    <%= will_paginate %>
    <ul class="responses" id="responses">
      <% @responses.each do |response| %>
        <li>
          <%= render partial: "shared/thought", object: response %>
          <% if current_user.admin? %>
            <%= link_to "delete", response, method: :delete, data: { confirm: "Are you sure?" } %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/responses/new.html.erb
<% provide(:page_title, "Respond") %>
<% provide(:page_description, "Tap your inner wisdom, let loose a witty repartée, give honest feedback, think critically, open minds") %>

<div class="row">
  <div class="well">
    <div class="col-md-10 col-md-offset-1">
      <div class="thought_wrapper">
        <div class="panel-focus">
          <div class="panel-post" id="show_post">
            <%= render partial: "shared/thought", object: @post %>
          </div>
          <%= render 'responder_links' %>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-8 col-md-offset-2" id="spacer">
        <p id="form_hint">
          You have 24 hours to respond to this post.  <%= link_to "Why 24 hours?", about_path %>
          Feel free to take your time when crafting a response.  If you need some inspiration browse some of the other <%= link_to "thoughts", posts_path %>.  Ready... Set... Reflect!
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <%= render partial: 'shared/form', object: @response %>
      </div>
    </div>
  </div>
</div>

app/views/responses/show.html.erb
<% provide(:page_title, "Response") %>

<div class="well">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <div class="posts_show">
          <%= render partial: "shared/thought", object: @post %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="container">
    <div class="col-md-10 col-md-offset-1">
      <div class="responses_show">
        <%= render partial: "shared/thought", object: @response %>
      </ul>
    </div>
    <% if author_or_follower(@post) %>
      <%= render 'ratings/form' unless current_user.id == @response.user.id %>
    <% end %>
  </div>
</div>