config/routes.rb
Thoughtsy::Application.routes.draw do
  get "password_resets/new"
  resources :users do
    resources :messages,  only: [:show, :index, :new]
  end
  resources :sessions,  only: [:new, :create, :destroy]
  resources :posts,     except: [:update, :edit] do
    resources :responses, only: [:new, :create]
    member do
      get 'flag'
      get 'language'
    end
    get 'queue', on: :collection
  end
  resources :ratings,   only: :create
  resources :responses, only: [:show, :destroy, :index]
  resources :password_resets, except: [:show, :index]
  resources :messages,  only: [:create, :destroy] do
    put 'view', on: :member
  end

  resources :images, only: [:new] do
    get 'remove', on: :collection
  end

  root 'static_pages#home'
  
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/team',    to: 'static_pages#team',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/queue',   to: 'posts#queue',          via: 'get'

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user, inverse_of: :posts, counter_cache: true
  
  has_many :responses
  has_many :responders, through: :responses, source: :user

  has_many :ratings, as: :rateable, dependent: :destroy
  has_many :raters, through: :ratings, source: :user

  mount_uploader :image, ImageUploader
  
  validates_presence_of :user_id
  validate :image_or_content

  after_create do |post|
    post.user.update_score!(1)
    post.add_unavailable_users(post.user)
    post.set_sort_date
  end


  scope :ascending,   -> { order('sort_date ASC') }
  scope :descending,  -> { order('sort_date DESC') }
  scope :ordered,     -> { order("CASE
                                    WHEN state = 'unanswered' THEN 1
                                    WHEN state = 'answered' OR state = 'pending' OR state = 'flagged' THEN 2
                                    WHEN state = 'unqueued' THEN 3
                                  END") }

  scope :queued,      -> { where("state = ? OR state = ?", "unanswered", "answered") }
  scope :answerable,  ->(user) { queued.where.not("? = ANY (unavailable_users)", user.id) }

  scope :answered,    -> { where("state = ? OR state = ?", "answered", "unqueued") }
  scope :personal,    -> { where.not("state = ? OR state = ?", "answered", "unqueued") }


  state_machine :state, initial: :unanswered do

    after_transition on: :flag do |post, transition|
      UserMailer.delay.flag_email(post)
      post.user.update_score!(-3)
    end

    after_transition on: :accept, do: :set_token_timer
    after_transition on: :expire, do: :reset_token_timer
    after_transition on: :answer do |post, transition| 
      post.set_sort_date
      post.unqueue! unless post.respondable?
    end

    event :accept do
      transition any => :pending
    end

    event :expire do
      transition :pending => :answered, :if => lambda { |post| post.responses.any? }
      transition :pending => :unanswered
    end

    event :answer do
      transition any => :answered
    end

    event :unanswer do
      transition any => :unanswered
    end

    event :flag do
      transition any => :flagged
    end

    event :unqueue do
      transition any => :unqueued
    end
  end

  def respondable?
    self.responses.size < 3 || self.avg_score >= 4
  end

  def avg_score
    if self.ratings.size != 0
      self.ratings.sum('value')/self.ratings.size
    else
      0
    end
  end

  def set_token_timer
    self.update_attribute(:token_timer, Time.zone.now) unless self.token_timer
  end

  def reset_token_timer
    self.update_attribute(:token_timer, nil)
  end

  def set_sort_date
    self.update_attribute(:sort_date, Time.zone.now)
  end

  def add_unavailable_users(user)
    unavailable_users_will_change!
    self.update_attribute(:unavailable_users, unavailable_users.push(user.id))
  end
  
  def remove_unavailable_users(user)
    unavailable_users_will_change!
    self.update_attribute(:unavailable_users, (unavailable_users.delete(user.id); unavailable_users))
  end                                         # delete returns deleted value rather than the array...

  ############# Heroku Scheduler ##############
  def Post.check_expirations
    pending_posts = Post.where(state: 'pending')
    pending_posts.each do |post|
      post.expire! if post.token_timer? && post.token_timer < 24.hours.ago
    end
  end

  ### Carrierwave-direct image upload helpers ###
  def image_name
    File.basename(image.path || image.filename) if image
  end

  def enqueue_image
    if has_image_upload? && !image_processed
      Delayed::Job.enqueue ImageProcessor.new(id, key)
    end
  end

  class ImageProcessor < Struct.new(:id, :key)
    def perform
      post = Post.find(id)
      post.key = key
      post.remote_image_url = post.image.direct_fog_url(with_path: true)
      post.update_column(:image_processed, true)
      post.save!
    end
  end

private

  def image_or_content
    errors.add(:base, "Post must include either an image or content") unless content.present? || has_image_upload?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :signed_in_user, except: [:index, :show]
  before_action :admin_user, only: [:destroy, :queue]
  before_action :tokened_responder, only: :flag

  def queue
    @posts = Post.where.not(state: "unqueued").ascending.ordered.paginate(page: params[:page])
  end

  def new
    @post = Post.new(key: params[:key])
  end

  def index
    @posts = Post.answered.descending.paginate(page: params[:page], :per_page => 20)
  end

  def show
    @post = Post.find(params[:id])
    @responses = @post.responses.descending
    @rating = Rating.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      @post.enqueue_image
      flash[:success] = "Post created!"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = @post.user
    @post.destroy!
    flash[:success] = "Post destroyed!"
    respond_to do |format|
      format.html { redirect_to :queue }
      format.js 
    end
  end

# Response#New #
  def flag
    @post = Post.find(params[:id])
    @token_post = Post.answerable(current_user).ascending.ordered.first
    @post.flag!       # sends flag_email on transition
    current_user.reset_tokens
    flash[:warning] = "Thought flagged."
    if @token_post
      redirect_to new_post_response_path(@token_post)
    else
      redirect_to root_url
    end
  end

  def language
    @post = Post.find(params[:id])
    @token_post = Post.answerable(current_user).ascending.ordered.first
    @post.expire!
    current_user.reset_tokens
    flash[:info] = "Thought reposted."
    if @token_post
      redirect_to new_post_response_path(@token_post)
    else
      redirect_to root_url
    end
  end
#

  private
    def post_params
      params.require(:post).permit(:content, :image, :key)
    end

    def rollback_tokens
      current_user.reset_tokens if signed_in? && !current_user.timer_valid
    end
end

app/helpers/posts_helper.rb
module PostsHelper

  ## to fix bug that very long words break the layout
    # raw method: prevent Rails from escaping the resulting HTML
    # sanitize method: needed to prevent cross-site scripting
    # ternary operator:  boolean?  ?  do one thing  :  (else:) do something else

  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end
    # split: divides str into substrings based on delimiter(default: whitespace)
    # map: applies wrap_long_string method to each substring(word)

  def custom_format(content)
    simple_format(sanitize(raw(content)))
  end
    # allows for n/ entered into content to be maintained in display
    # doesn't function properly when truncated

  def responded_time(thought)
    if thought.sort_date < 10.days.ago
      thought.sort_date.to_formatted_s(:short_ordinal)
    else
      "#{time_ago_in_words(thought.sort_date)} ago"
    end
  end

  def created_time(thought)
    if thought.created_at < 10.days.ago
      thought.created_at.to_formatted_s(:short_ordinal)
    else
      "#{time_ago_in_words(thought.created_at)} ago"
    end
  end

  def wrapped(content, length)
    truncate(wrap(content), length: length, separator: ' ')
  end

  def author_or_responder(post)
    (post.responders.include?(current_user) || current_user == post.user) if signed_in?
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text : text.scan(regex).join(zero_width_space)
    end
      # ZWS html character: white space which renders with zero width
      # scan(regex): breaks text into seperate 30 character strings in an array
      # join(ZWS): joins elements in array by ZWS and returns a string
end

app/views/posts/_index_post.html.erb
<div class="index_post">
  <h3>
    <div class="hidden-xs"><%= link_to gravatar_for(index_post.user, size: 50), user_path(index_post.user) %></div>
    <%= link_to wrapped(index_post.content, 200), post_path(index_post) unless index_post.content.nil? %>
    <div class="image">
      <%= render partial: 'shared/thumb', object: index_post, locals: { path: 'post_path(index_post)' } %>
    </div>
    <span class="label label-default">responded to <%= responded_time(index_post) %></span>
  </h3>
</div>

app/views/posts/_post.html.erb
<tr>
  <td><%= post.user.username %></td>
  <td><%= post.sort_date %> <%= "(#{post.created_at})" if post.responses.any? %></td>
  <td>
    <%= wrapped(post.content, 50) unless post.content.nil? %>
    <% if current_user.admin? && post.state == 'flagged' %>
      | <%= link_to "delete", post, method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
    <% if post.image? %>
      [image]
    <% end %>
  </td>
  <td><%= post.state %> <%= "(#{post.responses.count})" if post.responses.any? %></td>
</tr>


  

app/views/posts/_post_form.html.erb
<div id="post_form">
  <div class="panel-focus">
    <div class="panel-focus panel-post">
      <%= form_for(@post) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.text_area :content, class: "form-control", rows: "5", placeholder: "your thought..." %>
        <%= f.submit "Post", class: "btn btn-primary" %>
        <%= f.hidden_field :key %>
        <span class="pull-right">
          <% unless @post.has_image_upload? %>
            <%= link_to("Upload an image", new_image_path, :remote => true) %>
          <% else %>
            <strong>Image: </strong><%= @post.image_name %>
            | <%= link_to("remove", remove_images_path(key: params[:key])) %>
          <% end %>
        </span>
      <% end %>
    </div>
  </div>
</div>

<div class="modal" id="imageModal" style="display:none;">
</div>

app/views/posts/create.js.erb
var el = $('#new_post');
var flash = $('#js_flash_messages');

// remove error messages if present
$('#error_explanation').remove();

<% if !@post.save %>

  el.before("<%= escape_javascript(render('shared/error_messages', object: @post)) %>");
  el[0].reset();

<% else %>

  flash.html("<%= escape_javascript(render('shared/flash_messages')) %>");
  flash.fadeOut(5000);
  el[0].reset();
  // $('#post_count').html("<%= pluralize(current_user.posts.count, 'post') %>");

<% end %>

app/views/posts/destroy.js.erb
var posts = $('#link_<%= @post.id %>');
var flash = $('#js_flash_messages');

// calls flash message, updates post count
flash.html("<%= escape_javascript(render('shared/flash_messages')) %>");
flash.fadeOut(5000);
$('#post_count').html("Posts (<%= @user.posts.count %>)");

// remove post from view
posts.remove();

app/views/posts/flag.js.erb
var links = $('#responder_links');
var flash = $('#js_flash_messages');

$('#thought').html("<%= escape_javascript(render(partial: 'shared/thought', object: @token_post)) %>");

flash.html("<%= escape_javascript(render('shared/flash_messages')) %>");
flash.delay(3000).fadeOut('slow');

app/views/posts/index.html.erb
<% provide(:page_title, "Answered Thoughts") %>
<% provide(:page_description, "Browse some of the previous discussions") %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="well" id="posts_index">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <% if @posts.any? %>
            <h1>Answered Thoughts</h1>
          <% else %>
            <h3 class="empty">There are no answered thoughts</h3>
          <% end %>
          <% @posts.each do |post| %>
            <div class="panel-focus">
              <div class="panel-post">
                <%= render partial: 'index_post', object: post %>
              </div>
            </div>
          <% end %>
          <%= will_paginate %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<% provide(:page_title, "Post") %>
<% provide(:page_description, "Post a thought, pose a question, ask advice, show a piece of original art, share an anecdote, tell a story, inspire someone.") %>

<div class="row">
  <div class="well">
    <div class="row">
      <p id="form_hint">
        Not sure what to post?  Have a look at the <%= link_to "Guidelines", about_path %> or see what others have <%= link_to "posted", posts_path %>.
      </p>
      <div class="col-md-10 col-md-offset-1">
        <%= render partial: 'shared/form', object: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/queue.html.erb
<% provide(:page_title, "Queue") %>
<% provide(:page_description, "Admin dashboard") %>

<h1>Queue</h1>

<%= will_paginate %>

<table class="table table-striped">
  <thead>
    <td>Author</td>
    <td>Sort date (Created at)</td>
    <td>Content</td>
    <td>State (responses)</td>
  </thead>
  <tbody>
    <%= render @posts %>
  </tbody>
</table>

<%= will_paginate %>

app/views/posts/repost.js.erb
var links = $('#responder_links');
var flash = $('#js_flash_messages');

flash.html("<%= escape_javascript(render('shared/flash_messages')) %>");
flash.delay(3000).fadeOut('slow');
links.hide();

app/views/posts/show.html.erb
<% provide(:page_title, "Responses") %>
<% provide(:page_description, "See all responses to a thought") %>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="well" id="posts_show">
      <div class="thought_wrapper">
        <div class="panel-focus">
          <div class="panel-post" id="show_post">
            <%= render partial: "shared/thought", object: @post %>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <ul class="responses">
            <% @responses.each do |response| %>
              <li>
                <div class="thought_wrapper">
                  <div class="panel-focus">
                    <div class="panel-response">
                      <%= render partial: "shared/thought", object: response %>
                      <% if author_or_responder(@post) %>
                        <%= render partial: 'ratings/form', locals: { rateable: response } unless current_user.id == response.user.id %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>