config/routes.rb
Thoughtsy::Application.routes.draw do
  get "password_resets/new"
  resources :users do
    resources :messages,  only: [:show, :index, :new]
  end
  resources :sessions,  only: [:new, :create, :destroy]
  resources :posts,     except: [:update, :edit] do
    resources :responses, only: [:new, :create]
    member do
      get 'flag'
      get 'language'
    end
    get 'queue', on: :collection
  end
  resources :ratings,   only: :create
  resources :responses, only: [:show, :destroy, :index]
  resources :password_resets, except: [:show, :index]
  resources :messages,  only: [:create, :destroy] do
    put 'view', on: :member
  end

  resources :images, only: [:new] do
    get 'remove', on: :collection
  end

  root 'static_pages#home'
  
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/team',    to: 'static_pages#team',    via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/queue',   to: 'posts#queue',          via: 'get'

  

end

app/views/layouts/_analytics.html.erb
<!-- Google Analytics analytics.js Script -->
<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42916131-2', 'thoughtsy.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="cc_license">
    <a rel="license" href="http://creativecommons.org/licenses/by-sa/3.0/" target="_blank">CC License</a>
  </div class="cc_license">
  <nav>
    <ul>
      <li><%= link_to "Team",    team_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</div>

app/views/layouts/_ga.html.erb
<!-- Google Analytics ga.js script -->
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-42916131-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Thoughtsy", root_path, class: "navbar-brand", id: "brand" %>
  </div>
  
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <%= render 'layouts/notification_response' if signed_in? %>
      <%= render 'layouts/notification_message' if signed_in? %>
      <li><%= link_to "About",      about_path %></li>
      <li><%= link_to "Thoughts",   posts_path %></li>
    <% if signed_in? %>
      <li><%= link_to "Users",      users_path %></li>
      <li><%= link_to "Queue",      queue_path if user_admin? %><li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= current_user.username %> <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %> <i class="fa fa-user fa-fw"></i> </li>
          <li><%= link_to "Settings", edit_user_path(current_user) %> <i class="fa fa-cog fa-fw"></i> </li>
          <li><%= link_to "Messages", user_messages_path(current_user) %> <i class="fa fa-envelope fa-fw"></i> </li>
          <li class="divider"></li>
          <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
    <% end %>
    </ul>
  </div>
  <!-- /.navbar-collapse -->
  <div id="js_flash_messages">
    <%= render 'shared/flash_messages' %>
  </div>

</nav>

app/views/layouts/_notification_message.html.erb
<% if current_user.received_messages.unread.any? %>
  <li class="notifications" id="notification_message" data-placement="bottom" title="You have <%= unread_message_text(current_user) %>">
    <%= link_to('', user_messages_path(current_user), class: "fa fa-envelope") %>
  </li>
<% end %>

app/views/layouts/_notification_response.html.erb
<% if unrated_array(current_user).any? %>
  <li class="notifications" id="notification_response" data-toggle="tooltip" data-placement="bottom" title="You have <%= pluralize(unrated_array(current_user).count, 'unrated response') %>">
    <%= link_to('', unrated_response_path(current_user), class: "fa fa-comments") %>
  </li>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:page_title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= favicon_link_tag 'favicon.ico' %>
    <link href='//fonts.googleapis.com/css?family=Merienda:700' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,600,700,300' rel='stylesheet' type='text/css'>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="<%= yield(:page_description) %>">
    <%= render 'layouts/shim' %>
    <%= render 'layouts/ga' %>
  </head>
  <body>
    <div class="wrapper">
      <%= render 'layouts/header' %>
      <div class="container">
        <%= yield %>
        <div class="push"></div>
      </div>
    </div>
    <div class="footer">
      <%= render 'layouts/footer' %>
      <%= render 'layouts/analytics' %>
    </div>
  </body>
</html>